version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-producto-service  
    environment:
      POSTGRES_DB: producto_service_db         
      POSTGRES_USER: devdb
      POSTGRES_PASSWORD: a1b2c3d4
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"                           
    volumes:
      - postgres_producto_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devdb -d producto_service_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Opcional: pgAdmin con puerto diferente
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-producto-service  
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8083:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_producto_data:                     